Redux implementation
sarthak-sps/MoneyManagement pull request #1
Opened 2024-08-12 13:20 UTC by sarthak-sps

Added redux for state management. (For screens- add transaction, transactions, dashboard)
Made UI components dynamic.

2024-08-12 13:39 UTC, vaibhavsps1 commented on src/component/UpperComponent.js
> +                        <Image style={styles.profileImage} source={require('../../assets/images/applogo.png')} />
import this from utils/images file

2024-08-12 13:49 UTC, msssoftprodigy008 requested changes

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/AccountExpense.js
> +                    <Image style={styles.statusIcon} source={require('../../assets/images/expense.png')} />
Please move all image imports to a single file.

images.js
eg: const expense = require("path to image")

in component - 
import {expense} from 'path_image_file'

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/AccountIncomeStatus.js
> +                    <Image style={styles.statusIcon} source={require('../../assets/images/incomeArrow.png')} />
Please move all image imports to a single file.

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/AccountIncomeStatus.js
> +                    <Image source={require('../../assets/images/camera.png')} />
Please move all image imports to a single file.

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/TabView.js
> +            case 'Today':
Please move all constant values to a separate file.

constant.js
const TODAY = "Today"

component file
import {TODAY} from 'path_to_file'

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/UpperComponent.js
> +    const daysOfWeek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
Move all constant value to constant file

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/component/UpperComponent.js
> +    const monthsOfYear = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
Move all constant value to constant file

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/redux/reducer.js
> +        case 'ADD_TRANSACTION':
Create a separate action-type file for handling all cases.

action_type.js
const ADD_TRANSACTION = "ADD_TRANSACTION"

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/screens/AddTransactionScreen.js
> +    const categoryList = [
Move all constant value to constant file

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/screens/AddTransactionScreen.js
> +    const descriptionList = [
Move all constant value to constant file

2024-08-12 13:49 UTC, msssoftprodigy008 commented on src/screens/Profile.js
>            <Image source={require('../../assets/images/logout.png')} />
Move image to image file

2024-08-13 12:10 UTC, sarthak-sps commented on src/component/TabView.js
> +            case 'Today':
Implemented

2024-08-16 13:28 UTC, merged